ARCHS = armv7 arm64
TARGET_IPHONEOS_DEPLOYMENT_VERSION = 7.0

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DimSwitch
DimSwitch_FILES = Switch.x
DimSwitch_FRAMEWORKS = UIKit
DimSwitch_LIBRARIES = flipswitch
DimSwitch_INSTALL_PATH = /Library/Switches

include $(THEOS)/makefiles/bundle.mk