ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Dim
Dim_FILES = Switch.x
Dim_FRAMEWORKS = UIKit
Dim_LIBRARIES = flipswitch
Dim_INSTALL_PATH = /Library/Switches

include $(THEOS)/makefiles/bundle.mk
